version: "3"
services:
  klipper:
    image: flipper/klipper
    restart: unless-stopped
    privileged: true
    networks:
      - flipper-app
    volumes:
      - flipper-conf:/config
      - flipper-gcode:/gcode
      - flipper-tmp:/tmp
      - /dev/serial:/dev/serial
    entrypoint: /docker-entrypoint.sh
  moonraker:
    image: flipper/moonraker
    depends_on:
      - klipper
    restart: unless-stopped
    ports:
      - 7125:7125
    privileged: true
    networks:
      - flipper-app
    volumes:
      - flipper-conf:/config
      - flipper-gcode:/gcode
      - flipper-tmp:/tmp
      - /dev/serial:/dev/serial
    entrypoint: /docker-entrypoint.sh

  fluidd:
    image: flipper/fluidd
    depends_on:
      - moonraker
    restart: unless-stopped
    networks:
      - flipper-app
    ports:
      - 80:80
    environment:
      - UPSTREAM=192.168.4.9:7125

networks:
  flipper-app:
    driver: bridge

volumes:
  flipper-conf:
  flipper-gcode:
  flipper-tmp: