version: "3"
services:
  klipper:
    container_name: flipper-k
    image: flipper-klipper
    build: ./klipper
    restart: unless-stopped
    volumes:
      - config:/config
    networks:
      - flipper-app
    ports:
      - 7125:7125
    devices:
      - ${PRINTER_DEV}
  fluidd:
    container_name: flipper-f
    image: flipper-fluidd
    build: ./fluidd
    depends_on:
      - klipper
    restart: unless-stopped
    networks:
      - flipper-app
    ports:
      - 80:80
    environment:
      - UPSTREAM=${MR_UPSTREAM}

networks:
  flipper-app:
    driver: bridge

volumes:
  config:
