version: "3"
services:
  klipper:
    image: my-klipper
    restart: unless-stopped
    privileged: true
    volumes:
      - ConfVol:/config
      - GcodeVol:/gcode
      - TmpVol:/tmp
      - /dev/serial:/dev/serial
    entrypoint: /docker-entrypoint.sh
  moonraker:
    image: my-moonraker
    depends_on:
      - klipper
    restart: unless-stopped
    ports:
      - 7125:7125
    privileged: true
    volumes:
      - ConfVol:/config
      - GcodeVol:/gcode
      - TmpVol:/tmp
      - /dev/serial:/dev/serial
    entrypoint: /docker-entrypoint.sh

  fluidd:
    image: my-fluidd
    depends_on:
      - moonraker
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - UPSTREAM=192.168.4.9:7125

volumes:
  ConfVol:
  GcodeVol:
  TmpVol: