version: "3"
services:
  klipper:
    image: flipper-klipper
    build: ./klipper
    restart: unless-stopped
    networks:
      - flipper-app
    ports:
      - 7125:7125
    devices:
      - /dev/serial/by-id/usb-Klipper_lpc1769_20F0FF0B28813AAF13826A5CC02000F5-if00
  fluidd:
    image: flipper-fluidd
    build: ./fluidd
    depends_on:
      - klipper
    restart: unless-stopped
    networks:
      - flipper-app
    ports:
      - 80:80
    environment:
      - UPSTREAM=192.168.4.9:7125

networks:
  flipper-app:
    driver: bridge
